# Generated by Django 2.2 on 2021-02-19 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfileManager',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_stuff',
            new_name='is_staff',
        ),
    ]
